name: sync-devto
on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
    - run: npm run sync-devto --if-present
      env:
        FILES: 'posts/**/*.md'
        DEVTO_TOKEN: ${{ secrets.DEVTO_TOKEN }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}